spring:
  cloud:
    gateway:
      filter:
        local-response-cache:
          enabled: true
      routes:
        - id: download_area_code_service # https://www.data.go.kr/data/15000302/openapi.do
          uri: http://openapi.epost.go.kr
          predicates:
            - Method=GET
            - Path=/postal/downloadAreaCodeService/downloadAreaCodeService/{operation}
          filters:
            - AddResponseHeader=Vary, Accept
            - LocalResponseCache=${epost.openapi.proxy.routes.download_area_code_service.cache:10m,128MB}
          metadata:
            connect-timeout: ${epost.openapi.proxy.routes.retrieve_new_adress_area_cd_search_all_service.connect-timeout:1024}  # connect-timeout must be specified in milliseconds.
            response-timeout: ${epost.openapi.proxy.routes.retrieve_new_adress_area_cd_search_all_service.response-timeout:4096} # response-timeout must be specified in milliseconds.
        - id: retrieve_eng_address_service
          uri: http://openapi.epost.go.kr
          predicates:
            - Method=GET
            - Path=/postal/retrieveEngAddressService/retrieveEngAddressService/{operation}
          filters:
            - AddResponseHeader=Vary, Accept
            - LocalResponseCache=${epost.openapi.proxy.routes.retrieve_eng_address_service.cache.time:10m},${epost.openapi.proxy.routes.retrieve_eng_address_service.cache.size:128MB}
          metadata:
            connect-timeout: ${epost.openapi.proxy.routes.retrieve_eng_address_service.connect-timeout:1024}  # connect-timeout must be specified in milliseconds.
            response-timeout: ${epost.openapi.proxy.routes.retrieve_eng_address_service.response-timeout:4096} # response-timeout must be specified in milliseconds.
        - id: retrieve_lot_number_adress_area_cd_service # https://www.data.go.kr/iim/api/selectAPIAcountView.do
          uri: http://openapi.epost.go.kr
          predicates:
            - Method=GET
            - Path=/postal/retrieveLotNumberAdressAreaCdService/retrieveLotNumberAdressAreaCdService/{operation}
          filters:
            - AddResponseHeader=Vary, Accept
            - LocalResponseCache=${epost.openapi.proxy.routes.retrieve_lot_number_adress_area_cd_service.cache.time:10m},${epost.openapi.proxy.routes.retrieve_lot_number_adress_area_cd_service.cache.size:128MB}
          metadata:
            connect-timeout: ${epost.openapi.proxy.routes.retrieve_new_adress_area_cd_search_all_service.connect-timeout:1024}  # connect-timeout must be specified in milliseconds.
            response-timeout: ${epost.openapi.proxy.routes.retrieve_new_adress_area_cd_search_all_service.response-timeout:4096} # response-timeout must be specified in milliseconds.
        - id: retrieve_new_adress_area_cd_search_all_service
          uri: http://openapi.epost.go.kr
          predicates:
            - Method=GET
            - Path=/postal/retrieveNewAdressAreaCdSearchAllService/retrieveNewAdressAreaCdSearchAllService/{operation}
          filters:
            - AddResponseHeader=Vary, Accept
            - LocalResponseCache=${epost.openapi.proxy.routes.retrieve_new_adress_area_cd_search_all_service.cache:10m,128MB}
          metadata:
            connect-timeout: ${epost.openapi.proxy.routes.retrieve_new_adress_area_cd_search_all_service.connect-timeout:1024}  # connect-timeout must be specified in milliseconds.
            response-timeout: ${epost.openapi.proxy.routes.retrieve_new_adress_area_cd_search_all_service.response-timeout:4096} # response-timeout must be specified in milliseconds.
        - id: retrieve_new_adress_area_cd_service
          uri: http://openapi.epost.go.kr
          predicates:
            - Method=GET
            - Path=/postal/retrieveNewAdressAreaCdService/retrieveNewAdressAreaCdService/{operation}
          filters:
            - AddRequestParameter=ServiceKey, ${epost.openapi.proxy.service-key}
            - AddResponseHeader=Vary, Accept
            - LocalResponseCache=${epost.openapi.proxy.routes.retrieve_new_adress_area_cd_service.cache:10m,128MB}
          metadata:
            # https://docs.spring.io/spring-cloud-gateway/reference/spring-cloud-gateway/http-timeouts-configuration.html
            connect-timeout: ${epost.openapi.proxy.routes.retrieve_new_adress_area_cd_service.connect-timeout:1024}  # connect-timeout must be specified in milliseconds.
            response-timeout: ${epost.openapi.proxy.routes.retrieve_new_adress_area_cd_service.response-timeout:4096} # response-timeout must be specified in milliseconds.
#  jackson:
#    deserialization:
#      unwrap-root-value: true
