spring:
  application:
    name: epost-openapi-proxy
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      routes:
        - id: RetrieveNewAdressAreaCdService
          uri: http://openapi.epost.go.kr
          predicates:
            - Method=GET
            - Path=/postal/retrieveNewAdressAreaCdService/retrieveNewAdressAreaCdService/getNewAddressListAreaCd
          filters:
  profiles:
    group:
      epost-openapi-proxy-development:
